module.exports =
  Intro: require './Intro/Intro.view'
  DidYouKnow: require './DidYouKnow/DidYouKnow.view'
  Fares: require './Fares/Fares.view'
  Tips: require './Tips/Tips.view'
  FAQ: require './FAQ/FAQ.view'
  UpsidesDownsides: require './UpsidesDownsides/UpsidesDownsides.view'
  SavingsCalculator: require './SavingsCalculator/SavingsCalculator.view'
  Incentives: require './Incentives/Incentives.view'
  Amazon: require './Amazon/Amazon.view'
  SortableTable: require './SortableTable/SortableTable.view'
  WhatYouCanDo: require './WhatYouCanDo/WhatYouCanDo.view'
  Map: require './Map/Map.view'
  MapSearch: require './MapSearch/MapSearch.view'
  QuickTips: require './QuickTips/QuickTips.view'
  LeadingQuestion: require './LeadingQuestion/LeadingQuestion.view'
  Yelp: require './Yelp/Yelp.view'
  Images: require './Images/Images.view'
