module.exports =
  Intro: require './Intro/Intro.view'
  DidYouKnow: require './DidYouKnow/DidYouKnow.view'
  Fares: require './Fares/Fares.view'
  Tips: require './Tips/Tips.view'
  FAQ: require './FAQ/FAQ.view'
  UpsidesDownsides: require './UpsidesDownsides/UpsidesDownsides.view'
  SavingsCalculator: require './SavingsCalculator/SavingsCalculator.view'
  Incentives: require './Incentives/Incentives.view'
  Amazon: require './Amazon/Amazon.view'
  SortableTable: require './SortableTable/SortableTable.view'
  CallToAction: require './CallToAction/CallToAction.view'
  Map: require './Map/Map.view'
  QuickTips: require './QuickTips/QuickTips.view'
